/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import com.mycompany.linkkk.HibernateUtil;
import entity.Laporan;
import javax.swing.JOptionPane;
import org.hibernate.Session;
import org.hibernate.Transaction;

/**
 *
 * @author ASUS
 */
public class AdminEditLaporan extends javax.swing.JFrame {
    private entity.Laporan laporan;
    private entity.Admin adminLogin;

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AdminEditLaporan.class.getName());

    public AdminEditLaporan() {
        initComponents();
    }

    public AdminEditLaporan(entity.Laporan laporan, entity.Admin adminLogin) {
        initComponents();
        this.laporan = laporan;
        this.adminLogin = adminLogin;
        tampilkanDataLaporan(); 
    }

    private void tampilkanDataLaporan() {
        try {
            if (laporan != null) {
                txtIdLaporan.setText(laporan.getId_laporan());
                txtIdUser.setText(laporan.getUserPelapor() != null
                        ? laporan.getUserPelapor().getId_user()
                        : "-");
                txtJudul.setText(laporan.getJudul_laporan());
                txtIsi.setText(laporan.getIsi_laporan());
                txtKategoriLaporan.setText(laporan.getKategori() != null ? laporan.getKategori() : "-");
                txtBukti.setText(laporan.getBukti() != null ? laporan.getBukti() : "-");
                txtTanggal.setText(laporan.getTanggal_laporan() != null ? laporan.getTanggal_laporan().toString() : "-");
                txtTingkatKeparahan.setText(
                        laporan.getTingkat_keparahan() != null
                                ? laporan.getTingkat_keparahan().toString()
                                : "0"
                );

                txtIdLaporan.setEditable(false);
                txtIdUser.setEditable(false);
                txtJudul.setEditable(false);
                txtIsi.setEditable(false);
                txtKategoriLaporan.setEditable(false);
                txtBukti.setEditable(false);
                txtTanggal.setEditable(false);

                txtTingkatKeparahan.setEditable(true);
            } else {
                JOptionPane.showMessageDialog(this,
                        "Data laporan tidak ditemukan!",
                        "Peringatan", JOptionPane.WARNING_MESSAGE);
            }
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal menampilkan data laporan", e);
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat menampilkan data laporan.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnSimpan = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtTingkatKeparahan = new javax.swing.JTextField();
        txtTanggal = new javax.swing.JTextField();
        txtBukti = new javax.swing.JTextField();
        txtIsi = new javax.swing.JTextField();
        txtKategoriLaporan = new javax.swing.JTextField();
        txtJudul = new javax.swing.JTextField();
        txtIdUser = new javax.swing.JTextField();
        txtIdLaporan = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 560));
        setResizable(false);
        getContentPane().setLayout(null);

        btnSimpan.setBackground(new java.awt.Color(80, 191, 126));
        btnSimpan.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnSimpan.setForeground(new java.awt.Color(255, 255, 255));
        btnSimpan.setText("Simpan Perubahan");
        btnSimpan.setBorder(null);
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });
        getContentPane().add(btnSimpan);
        btnSimpan.setBounds(590, 120, 140, 40);

        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Kembali");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 130, 130, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel8.setText("Data Laporan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(10, 40, 170, 60);

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel9.setText("Isi Laporan");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(30, 440, 80, 20);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel10.setText("Kategori Laporan");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(30, 380, 90, 20);

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel11.setText("Judul Laporan");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(30, 320, 80, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel12.setText("ID User");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(30, 260, 80, 20);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel13.setText("ID Laporan");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(30, 200, 80, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel14.setText("Tanggal Laporan");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(410, 260, 80, 20);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel15.setText("Tingkat Keparahan ( 0.0 - 5.0 )");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(410, 314, 160, 30);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel16.setText("Bukti");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(410, 200, 80, 20);

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2);
        jLabel2.setBounds(20, 126, 90, 30);
        getContentPane().add(txtTingkatKeparahan);
        txtTingkatKeparahan.setBounds(410, 340, 300, 30);

        txtTanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTanggalActionPerformed(evt);
            }
        });
        getContentPane().add(txtTanggal);
        txtTanggal.setBounds(410, 280, 300, 30);

        txtBukti.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBuktiActionPerformed(evt);
            }
        });
        getContentPane().add(txtBukti);
        txtBukti.setBounds(410, 220, 300, 30);

        txtIsi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIsiActionPerformed(evt);
            }
        });
        getContentPane().add(txtIsi);
        txtIsi.setBounds(30, 460, 300, 30);

        txtKategoriLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKategoriLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(txtKategoriLaporan);
        txtKategoriLaporan.setBounds(30, 400, 300, 30);

        txtJudul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJudulActionPerformed(evt);
            }
        });
        getContentPane().add(txtJudul);
        txtJudul.setBounds(30, 340, 300, 30);
        getContentPane().add(txtIdUser);
        txtIdUser.setBounds(30, 280, 300, 30);

        txtIdLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdLaporanActionPerformed(evt);
            }
        });
        getContentPane().add(txtIdLaporan);
        txtIdLaporan.setBounds(30, 220, 300, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Admin Edit Laporan.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 760, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtTanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTanggalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTanggalActionPerformed

    private void txtBuktiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBuktiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBuktiActionPerformed

    private void txtJudulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJudulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJudulActionPerformed

    private void txtKategoriLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKategoriLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKategoriLaporanActionPerformed

    private void txtIsiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIsiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIsiActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        String tingkatStr = txtTingkatKeparahan.getText().trim();

        if (tingkatStr.isEmpty()) {
            JOptionPane.showMessageDialog(this,
                    "Tingkat Keparahan tidak boleh kosong!",
                    "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        try {
            double tingkat = Double.parseDouble(tingkatStr);

            if (tingkat < 0.0 || tingkat > 5.0) {
                JOptionPane.showMessageDialog(this,
                        "Nilai Tingkat Keparahan harus berada antara 0.0 dan 5.0!",
                        "Input Tidak Valid", JOptionPane.WARNING_MESSAGE);
                return;
            }

            try (Session session = HibernateUtil.getSessionFactory().openSession()) {
                Transaction tx = session.beginTransaction();

                Laporan update = session.get(Laporan.class, txtIdLaporan.getText());
                if (update != null) {
                    update.setTingkat_keparahan(tingkat);
                    session.update(update);
                    tx.commit();

                    JOptionPane.showMessageDialog(this,
                            "Perubahan berhasil disimpan!",
                            "Sukses", JOptionPane.INFORMATION_MESSAGE);

                    logger.info("Admin " + (adminLogin != null ? adminLogin.getId_user() : "unknown")
                            + " mengubah tingkat keparahan laporan ID: " + update.getId_laporan());
                } else {
                    JOptionPane.showMessageDialog(this,
                            "Laporan tidak ditemukan!",
                            "Error", JOptionPane.ERROR_MESSAGE);
                }
            } catch (Exception e) {
                logger.log(java.util.logging.Level.SEVERE, "Gagal menyimpan perubahan laporan", e);
                JOptionPane.showMessageDialog(this,
                        "Terjadi kesalahan saat menyimpan data: " + e.getMessage(),
                        "Kesalahan", JOptionPane.ERROR_MESSAGE);
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this,
                    "Masukkan angka valid untuk tingkat keparahan!",
                    "Error", JOptionPane.ERROR_MESSAGE);
        }   
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtIdLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdLaporanActionPerformed

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        new AdminBagianMembacaLaporan(adminLogin).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel7MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info :
                    javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new AdminEditLaporan().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField txtBukti;
    private javax.swing.JTextField txtIdLaporan;
    private javax.swing.JTextField txtIdUser;
    private javax.swing.JTextField txtIsi;
    private javax.swing.JTextField txtJudul;
    private javax.swing.JTextField txtKategoriLaporan;
    private javax.swing.JTextField txtTanggal;
    private javax.swing.JTextField txtTingkatKeparahan;
    // End of variables declaration//GEN-END:variables
}
