/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;

import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class BerandaAdmin extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(BerandaAdmin.class.getName());
    private entity.Admin adminLogin;

    
    private void loadTanggapanCounts() {
        try {
            Dao.TanggapanDao dao = new Dao.TanggapanIml();

            long diterima = dao.countByStatus("Diterima");
            long proses = dao.countByStatus("Dalam_Proses");
            long selesai = dao.countByStatus("Selesai");
            long ditolak = dao.countByStatus("Ditolak");

            lpDiterima.setText(String.valueOf(diterima));
            lpDiproses.setText(String.valueOf(proses));
            lpSelesai.setText(String.valueOf(selesai));
            lpDitolak.setText(String.valueOf(ditolak));
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data tanggapan", e);
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat memuat data tanggapan.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadDashboardStats() {
        try {
            Dao.LaporanDao laporanDao = new Dao.LaporanIml();
            Dao.UserDao userDao = new Dao.UserIml();

            long totalLaporan = laporanDao.countAll();
            long totalUser = userDao.countAllUsers();
            String kategoriTerbanyak = laporanDao.getMostFrequentKategori();

            ttlLM.setText(totalLaporan + " Laporan");
            ttlPT.setText(totalUser + " Pengguna");
            ttlKT.setText(kategoriTerbanyak != null ? kategoriTerbanyak : "Belum Ada");
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat statistik dashboard", e);
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat memuat statistik dashboard.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    
    private void loadLembagaCounts() {
        try {
            Dao.LembagaIDao dao = new Dao.LembagaIml();

            long penegak = dao.countByJenis("Penegak_Hukum");
            long antiKorupsi = dao.countByJenis("Anti_Korupsi_Pengawasan");
            long perlindungan = dao.countByJenis("Perlindungan_Pencegahan_Kekerasan");
            long etika = dao.countByJenis("Etika_Transparansi");

            jlph.setText(String.valueOf(penegak));
            jlakp.setText(String.valueOf(antiKorupsi));
            jlppk.setText(String.valueOf(perlindungan));
            jlet.setText(String.valueOf(etika));
        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data lembaga", e);
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat memuat data lembaga.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }
    
   
    public BerandaAdmin(entity.Admin adminLogin) {
        initComponents();
        this.adminLogin = adminLogin;

        try {
            if (adminLogin != null) {
                System.out.println("DEBUG: Admin login ID = " + adminLogin.getId_user());
            } else {
                System.out.println("DEBUG: Admin login = null");
            }

            loadTanggapanCounts();
            loadDashboardStats();
            loadLembagaCounts();
            tampilkanNamaAdmin();

        } catch (Exception e) {
            logger.log(java.util.logging.Level.SEVERE, "Gagal memuat data awal BerandaAdmin", e);
            JOptionPane.showMessageDialog(this,
                    "Terjadi kesalahan saat memuat data awal dashboard admin.",
                    "Kesalahan", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void tampilkanNamaAdmin() {
        try {
            if (adminLogin != null && adminLogin.getNama() != null) {
                String namaAdmin = adminLogin.getNama();
                jLabel3.setText("Selamat Datang Kembali, " + namaAdmin + "!");
            } else {
                jLabel3.setText("Selamat Datang Kembali, Admin!");
            }
        } catch (Exception e) {
            jLabel3.setText("Selamat Datang Kembali, Admin!");
            System.err.println("Gagal menampilkan nama admin: " + e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        lpDitolak = new javax.swing.JLabel();
        lpSelesai = new javax.swing.JLabel();
        lpDiproses = new javax.swing.JLabel();
        ttlLM = new javax.swing.JLabel();
        ttlPT = new javax.swing.JLabel();
        ttlKT = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jlakp = new javax.swing.JLabel();
        lpDiterima = new javax.swing.JLabel();
        jlppk = new javax.swing.JLabel();
        jlet = new javax.swing.JLabel();
        jlph = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(750, 560));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Diterima");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(180, 160, 90, 30);

        jLabel3.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel3.setText("Selamat Datang Kembali, Admin!");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(160, 70, 560, 40);

        jLabel4.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Sedang Proses");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(320, 160, 110, 30);

        jLabel5.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Selesai");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(480, 160, 60, 30);

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 10)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Ditolak");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(640, 160, 60, 30);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 102, 204));
        jLabel7.setText("Lembaga Terhubung");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(370, 410, 160, 30);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(102, 102, 102));
        jLabel8.setText("Pengawasan");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(330, 490, 90, 20);

        jLabel9.setText("Kelola laporan masyarakat dengan integritas dan tanggung jawab.");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(160, 100, 570, 30);

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(102, 102, 102));
        jLabel13.setText("Anti Korupsi &");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(320, 470, 120, 30);

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(102, 102, 102));
        jLabel15.setText("Pelindungan &");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(470, 470, 90, 30);

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(102, 102, 102));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Kekerasan");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(520, 490, 70, 20);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Pencegahan");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(450, 490, 80, 20);

        jLabel18.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(102, 102, 102));
        jLabel18.setText("Etika &");
        getContentPane().add(jLabel18);
        jLabel18.setBounds(650, 470, 50, 30);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setForeground(new java.awt.Color(102, 102, 102));
        jLabel19.setText("Transparansi");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(630, 490, 80, 20);

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(102, 102, 102));
        jLabel21.setText("Penegak Hukum");
        getContentPane().add(jLabel21);
        jLabel21.setBounds(170, 470, 100, 30);

        lpDitolak.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lpDitolak.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpDitolak.setText("290");
        getContentPane().add(lpDitolak);
        lpDitolak.setBounds(600, 190, 80, 30);

        lpSelesai.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lpSelesai.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpSelesai.setText("500");
        getContentPane().add(lpSelesai);
        lpSelesai.setBounds(460, 190, 70, 30);

        lpDiproses.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lpDiproses.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpDiproses.setText("290");
        getContentPane().add(lpDiproses);
        lpDiproses.setBounds(300, 190, 70, 30);

        ttlLM.setFont(new java.awt.Font("Segoe UI Historic", 1, 13)); // NOI18N
        ttlLM.setForeground(new java.awt.Color(255, 255, 255));
        ttlLM.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ttlLM);
        ttlLM.setBounds(150, 360, 180, 40);

        ttlPT.setForeground(new java.awt.Color(255, 255, 255));
        ttlPT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ttlPT);
        ttlPT.setBounds(350, 360, 180, 40);

        ttlKT.setForeground(new java.awt.Color(255, 255, 255));
        ttlKT.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        getContentPane().add(ttlKT);
        ttlKT.setBounds(550, 360, 180, 40);

        jLabel20.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel20.setForeground(new java.awt.Color(255, 255, 255));
        jLabel20.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel20.setText("Total Laporan Masuk");
        getContentPane().add(jLabel20);
        jLabel20.setBounds(160, 260, 140, 40);

        jLabel11.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Total Pengguna Terdaftar");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(340, 270, 200, 20);

        jLabel12.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Kategori Laporan");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(550, 270, 130, 20);

        jLabel14.setFont(new java.awt.Font("Segoe UI Historic", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Terbanyak");
        getContentPane().add(jLabel14);
        jLabel14.setBounds(560, 290, 100, 20);

        jlakp.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jlakp.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlakp.setText("50");
        getContentPane().add(jlakp);
        jlakp.setBounds(330, 450, 70, 30);

        lpDiterima.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        lpDiterima.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lpDiterima.setText("128");
        lpDiterima.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                lpDiterimaPropertyChange(evt);
            }
        });
        getContentPane().add(lpDiterima);
        lpDiterima.setBounds(150, 190, 60, 30);

        jlppk.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jlppk.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlppk.setText("40");
        getContentPane().add(jlppk);
        jlppk.setBounds(480, 450, 70, 30);

        jlet.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jlet.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlet.setText("10");
        getContentPane().add(jlet);
        jlet.setBounds(630, 450, 70, 30);

        jlph.setFont(new java.awt.Font("Segoe UI Historic", 1, 18)); // NOI18N
        jlph.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlph.setText("20");
        getContentPane().add(jlph);
        jlph.setBounds(180, 450, 70, 30);

        jLabel23.setForeground(new java.awt.Color(255, 255, 255));
        jLabel23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel23.setText("Keluar");
        jLabel23.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jLabel23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel23MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel23);
        jLabel23.setBounds(653, 10, 70, 20);

        jLabel24.setText("Tanggapan");
        jLabel24.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel24MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel24);
        jLabel24.setBounds(50, 90, 80, 20);

        jLabel25.setText("Lembaga");
        jLabel25.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel25MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel25);
        jLabel25.setBounds(50, 110, 80, 20);

        jLabel26.setText("  Laporan");
        jLabel26.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel26MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel26);
        jLabel26.setBounds(43, 70, 90, 16);

        jLabel27.setText("Beranda");
        jLabel27.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel27MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel27);
        jLabel27.setBounds(30, 50, 100, 16);

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Beranda Admin.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(0, 0, 750, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lpDiterimaPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_lpDiterimaPropertyChange
        // TODO add your handling code here:
    }//GEN-LAST:event_lpDiterimaPropertyChange

    private void jLabel27MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel27MouseClicked
        new BerandaAdmin(adminLogin).setVisible(true);
        this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel27MouseClicked

    private void jLabel26MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel26MouseClicked
    new AdminBagianMembacaLaporan(adminLogin).setVisible(true); 
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel26MouseClicked

    private void jLabel24MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel24MouseClicked
    new AdminBagianMembacaTanggapan(adminLogin).setVisible(true);
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel24MouseClicked

    private void jLabel25MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel25MouseClicked
    new AdminBagianMembacaLembaga(adminLogin).setVisible(true); 
    this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel25MouseClicked

    private void jLabel23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel23MouseClicked
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Apakah Anda yakin ingin keluar?",
            "Konfirmasi Logout",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm == JOptionPane.YES_OPTION) {
            this.dispose();
            new Home().setVisible(true);
        }
    }//GEN-LAST:event_jLabel23MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jlakp;
    private javax.swing.JLabel jlet;
    private javax.swing.JLabel jlph;
    private javax.swing.JLabel jlppk;
    private javax.swing.JLabel lpDiproses;
    private javax.swing.JLabel lpDiterima;
    private javax.swing.JLabel lpDitolak;
    private javax.swing.JLabel lpSelesai;
    private javax.swing.JLabel ttlKT;
    private javax.swing.JLabel ttlLM;
    private javax.swing.JLabel ttlPT;
    // End of variables declaration//GEN-END:variables
}
