/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frame;


/**
 *
 * @author ASUS
 */
public class Guide extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Guide.class.getName());

    /**
     * Creates new form Guide
     */public Guide() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Register2 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        Register = new javax.swing.JButton();
        Register1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        Register2.setText("Register");
        Register2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Register2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register2ActionPerformed(evt);
            }
        });

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(750, 533));
        setPreferredSize(new java.awt.Dimension(748, 560));
        setResizable(false);
        getContentPane().setLayout(null);

        jLabel2.setText("2. Masuk ke Dashboard");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(30, 144, 332, 16);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("Bagaimana TruthLink Bekerja");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(30, 50, 510, 50);

        jLabel4.setText("Langkah-langkah sederhana untuk memulai pelaporan:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(30, 100, 320, 20);

        jLabel5.setText("1. Daftar Akun");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 116, 370, 16);

        jLabel6.setText("6. Terima Tanggapan");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 264, 420, 20);

        jLabel7.setText("Buat akun baru untuk mengakses sistem pelaporan TruthLink.");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(50, 130, 330, 16);

        jLabel12.setText("© 2025 TruthLink — Developed by the TruthLink Team, Mulawarman University");
        getContentPane().add(jLabel12);
        jLabel12.setBounds(170, 496, 500, 40);

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(102, 102, 102));
        jLabel16.setText("Identitas Anda akan dijaga dengan aman dan rahasia.");
        getContentPane().add(jLabel16);
        jLabel16.setBounds(40, 470, 200, 20);

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 8)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(102, 102, 102));
        jLabel22.setText("Setiap laporan membantu mewujudkan keadilan dan transparansi publik.");
        getContentPane().add(jLabel22);
        jLabel22.setBounds(40, 480, 280, 20);

        jLabel30.setText("4. Proses Verifikasi");
        getContentPane().add(jLabel30);
        jLabel30.setBounds(30, 204, 290, 16);

        jLabel31.setText("Tulis laporan dengan informasi dan bukti yang lengkap.");
        getContentPane().add(jLabel31);
        jLabel31.setBounds(50, 190, 310, 16);

        jLabel32.setText("3. Kirim Laporan");
        getContentPane().add(jLabel32);
        jLabel32.setBounds(30, 176, 120, 16);

        jLabel33.setText("Login ke akun Anda untuk mulai membuat laporan.");
        getContentPane().add(jLabel33);
        jLabel33.setBounds(50, 160, 290, 16);

        jLabel34.setText("Lacak status laporan Anda melalui menu Riwayat.");
        getContentPane().add(jLabel34);
        jLabel34.setBounds(50, 250, 420, 16);

        jLabel35.setText("Dapatkan pembaruan dan umpan balik dari tim admin.");
        getContentPane().add(jLabel35);
        jLabel35.setBounds(50, 280, 420, 16);

        jLabel36.setText("5. Pantau Perkembangan");
        getContentPane().add(jLabel36);
        jLabel36.setBounds(30, 234, 420, 16);

        jLabel37.setText("Tim admin memeriksa dan meneruskan laporan Anda ke instansi berwenang.");
        getContentPane().add(jLabel37);
        jLabel37.setBounds(50, 220, 420, 16);

        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel19.setText("Daftar & Masuk");
        getContentPane().add(jLabel19);
        jLabel19.setBounds(60, 390, 100, 16);

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel38.setText("Buat akun Anda dan masuk ");
        getContentPane().add(jLabel38);
        jLabel38.setBounds(50, 410, 130, 14);

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel39.setText("ke dasbor pribadi Anda.");
        getContentPane().add(jLabel39);
        jLabel39.setBounds(60, 420, 120, 20);

        jLabel40.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel40.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel40.setText("Kirim Laporan");
        getContentPane().add(jLabel40);
        jLabel40.setBounds(190, 390, 110, 16);

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel41.setText("Tulis dan kirim laporan Anda");
        getContentPane().add(jLabel41);
        jLabel41.setBounds(180, 410, 136, 14);

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel42.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel42.setText("dengan informasi dan bukti");
        getContentPane().add(jLabel42);
        jLabel42.setBounds(160, 420, 150, 20);

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel43.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel43.setText("yang lengkap");
        getContentPane().add(jLabel43);
        jLabel43.setBounds(200, 440, 90, 14);

        jLabel44.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel44.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel44.setText("Proses Verifikasi");
        getContentPane().add(jLabel44);
        jLabel44.setBounds(320, 390, 120, 16);

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel45.setText("Admin akan meninjau dan");
        getContentPane().add(jLabel45);
        jLabel45.setBounds(320, 410, 130, 14);

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel46.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel46.setText("memverifikasi laporan Anda.");
        getContentPane().add(jLabel46);
        jLabel46.setBounds(310, 420, 140, 20);

        jLabel47.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel47.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel47.setText("Lacak Perkembangan");
        getContentPane().add(jLabel47);
        jLabel47.setBounds(440, 390, 140, 16);

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel48.setText("Pantau status laporan Anda");
        getContentPane().add(jLabel48);
        jLabel48.setBounds(450, 410, 130, 14);

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel49.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel49.setText("melalui halaman Riwayat.");
        getContentPane().add(jLabel49);
        jLabel49.setBounds(450, 420, 120, 20);

        jLabel50.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel50.setText(" Terima Tanggapan");
        getContentPane().add(jLabel50);
        jLabel50.setBounds(580, 390, 120, 16);

        jLabel51.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel51.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel51.setText("Dapatkan balasan atau");
        getContentPane().add(jLabel51);
        jLabel51.setBounds(580, 410, 110, 14);

        jLabel52.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel52.setText("pembaruan akhir dari tim");
        getContentPane().add(jLabel52);
        jLabel52.setBounds(580, 420, 120, 20);

        jLabel53.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        jLabel53.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel53.setText("admin.");
        getContentPane().add(jLabel53);
        jLabel53.setBounds(600, 440, 70, 14);

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Panduan");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel8);
        jLabel8.setBounds(420, 10, 70, 20);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Lainnya");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel9);
        jLabel9.setBounds(490, 10, 60, 20);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Tentang kami");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel10);
        jLabel10.setBounds(330, 10, 90, 20);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Beranda");
        jLabel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel11MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel11);
        jLabel11.setBounds(260, 10, 70, 20);

        Register.setBackground(new java.awt.Color(24, 55, 106));
        Register.setForeground(new java.awt.Color(255, 255, 255));
        Register.setText("Masuk");
        Register.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255), 3));
        Register.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterActionPerformed(evt);
            }
        });
        getContentPane().add(Register);
        Register.setBounds(570, 10, 70, 30);

        Register1.setText("Daftar");
        Register1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Register1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Register1ActionPerformed(evt);
            }
        });
        getContentPane().add(Register1);
        Register1.setBounds(650, 10, 80, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/picture/Guide Guess.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 750, 530);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void RegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterActionPerformed
        Register registerPage = new Register();
        registerPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_RegisterActionPerformed

    private void Register1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register1ActionPerformed
        Register registerPage = new Register();
        registerPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Register1ActionPerformed

    private void Register2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Register2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Register2ActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        Guide guidePage = new Guide();
        guidePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        Others othersPage = new Others();
        othersPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        AboutUs aboutPage = new AboutUs();
        aboutPage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel11MouseClicked
        Home homePage = new Home();
        homePage.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jLabel11MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Guide().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Register;
    private javax.swing.JButton Register1;
    private javax.swing.JButton Register2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
